config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :admins do
    resources :users
    resources :products
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :product, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategorysController < AdminsController
 
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def create 
    @category = Category.new(product_params) 
    # @category.category_id = params[:category_id] 
    if @category.save 
       render @category
    else 
        render new
    end 
  end 
    
  def update
    @category = Category.params.require(:product_id).permit(:admin, :users)

  end

  def destroy
    @category = Category.params[:category_id] 
    @category.destroy
  end

 private
 
 def product_params
    params.require(:Category).permit(:category_id, :category_name)
 end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminsController
  def index
    @order = Order.all

  end
  def create
  
  end
  def destroy
    @order = Order.params[:order_id,:order_name]
    @order.destroy
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminsController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
      params[:products][:user_id] = current_user.id
      @products = Product.new(products_params)
      if @product.after_save 
        render Product
      else
        flash[:error] ='Can not save'
        render 'new'
      end
  end

  def edit
    @products = Product.find(params[:id])
  end

  def update
    @products = Products.find(params[:id])
    @products.update_attributes!(products_params)
    flash[:notice] = "#{@products.name} has been succesfully updated."
    redirect_to root_path
  end

  def destroy
    @products = Product.find(params[:id])
    @products.destroy
    flash[:notice] = "Your product '#{@products.name}' has been deleted."
    redirect_to root_path
  end

  def show
    @products = Product.find(params[:id])
  end

private
def products_params
  params.require(:product).permit(:product_id, :product_name)
end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminsController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def destroy
    @user = User.params.require(:user).permit(:user_id)
  end
  

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
 before_action :is_admin?

 private
def is_admin?
  redirect_to root_path unless current_user&.admin?
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
        keys: [:username, :name, :email, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:sign_in,
        keys: [:login, :password, :password_confirmation])
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    if params[:category_id]
      @products = Product.where(category_id: params[:category_id])
    else
      @products = Product.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/categorys_helper.rb
module Admin::CategorysHelper
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/products/index.html.erb
<% @categories.each do |category| %>
 <%= link_to category.category_name, root_path + "?category_id=#{category.id}" %><br>
 <% end %>   
     <table class="zsd table table-bordered table-striped">   
       <tr>   
        <th>Name</th>   
        <th>Price</th>   
        <th>Description</th>   
          
      </tr>   
       
      <% @products.each do |product| %>   
          <tr>   
            <td><%= product.product_name %></td>   
            <td><%= product.product_price %></td>   
            <td><%= truncate(product.product_description, :length => 75) %></td>   
           
           </tr>   
      <% end %>   
    </table>

app/views/admins/products/new.html.erb
<%= form_for @product, url: admin_products_path do |f| %>        
<%= f.label :product_name %>   
<%= f.text_field :product_name %> 

<%= f.label :product_price %>   
<%= f.text_field :product_price %> 

<%= f.label :product_description %>   
<%= f.text_field :product_description %>   

<%= f.submit 'submit' %>   
    
<% end %>   

app/views/admins/products/show.html.erb
<h1>this is product</h1>
<%= @products.each do |product| %>
<%= product.product_name %>
<%= product.product_price %>
<%= product.product_description %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>